{
  "openapi": "3.0.0",
  "info": {
    "title": "Words API",
    "description": "Words API lets you retrieve information about English words, including definitions, synonyms, rhymes, pronunciation, syllables, and frequency of usage. It also can tell you about relationships between words, for instance that “math” has categories like “algebra” and “geometry”, or that a “finger” is part of a “hand”.",
    "contact": {
      "name": "Muhammad Sufyan",
      "url": "apimatic.io",
      "email": "muhammad.sufyan@apimatic.io"
    },
    "version": "1.0.2"
  },
  "servers": [
    {
      "url": "https://wordsapiv1.p.rapidapi.com",
      "variables": {}
    }
  ],
  "paths": {
    "/words/{word}/synonyms": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Synonyms",
        "description": "Get synonyms of a word.",
        "operationId": "Synonyms",
        "parameters": [
          {
            "name": "word",
            "in": "path",
            "description": "The word to search synonyms for.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "lovely"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SynonymsResponse"
                },
                "example": {
                  "word": "lovely",
                  "synonyms": [
                    "adorable",
                    "endearing",
                    "cover girl",
                    "pin-up"
                  ]
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/words/{word}/definitions": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Definitions",
        "description": "Get definitions of a word, including the part of speech.",
        "operationId": "Definitions",
        "parameters": [
          {
            "name": "word",
            "in": "path",
            "description": "The word to search the definitions for.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "lovely"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DefinitionsResponse"
                },
                "example": {
                  "word": "lovely",
                  "definition": [
                    "lovable especially in a childlike or naive way",
                    "a very pretty girl who works as a photographer's model",
                    "appealing to the emotions as well as the eye"
                  ]
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/words/{word}/pronunciation": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Pronunciation",
        "description": "How to pronounce a word, according to the International Phonetic Alphabet. May include multiple results if the word is pronounced differently depending on its part of speech.",
        "operationId": "Pronunciation",
        "parameters": [
          {
            "name": "word",
            "in": "path",
            "description": "The word to search pronunciation for.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "wind"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PronunciationResponse"
                },
                "example": {
                  "word": "wind",
                  "pronunciation": {
                    "all": "wɪnd",
                    "noun": "wɪnd",
                    "verb": "waɪnd"
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/words/{word}": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Word",
        "description": "Retrieve information about a word. Results can include definitions, part of speech, synonyms, related words, syllables, and pronunciation. This method is useful to see which relationships are attached to which definition and part of speech of a word.",
        "operationId": "Word",
        "parameters": [
          {
            "name": "word",
            "in": "path",
            "description": "This is a template parameter that is used to provide the word, about which the information is being fetched.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "Testing"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WordResponse"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/words/{word}/examples": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Examples",
        "description": "Get examples of how the word is used.",
        "operationId": "Examples",
        "parameters": [
          {
            "name": "word",
            "in": "path",
            "description": "The word to search the examples for.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "wind"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ExamplesResponse"
                },
                "example": {
                  "word": "testing",
                  "examples": [
                    "there are laboratories for commercial testing",
                    "it involved testing thousands of children for smallpox",
                    "they agreed to end the testing of atomic weapons"
                  ]
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/words/{word}/frequency": {
      "get": {
        "tags": [
          "APIs"
        ],
        "summary": "Frequency",
        "description": "Expands upon the frequency score returned by the main /words/{word} endpoint. Returns zipf, a score indicating how common the word is in the English language, with a range of 1 to 7; per Million, the number of times the word is likely to appear in a corpus of one million English words; and diversity, a 0-1 scale the shows the likelihood of the word appearing in an English document that is part of a corpus.",
        "operationId": "Frequency",
        "parameters": [
          {
            "name": "word",
            "in": "path",
            "description": "The word to search frequency for.",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "lovely"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FrequencyResponse"
                },
                "example": {
                  "word": "wind",
                  "frequency": {
                    "zipf": 4.81,
                    "perMillion": 64.22,
                    "diversity": 0.2
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "DefinitionsResponse": {
        "title": "DefinitionsResponse",
        "type": "object",
        "properties": {
          "word": {
            "type": "string",
            "description": "The word that is searched.",
            "nullable": true,
            "example": "lovely"
          },
          "definition": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The definitions of the searched word.",
            "nullable": true,
            "example": [
              "lovable especially in a childlike or naive way",
              "a very pretty girl who works as a photographer's model",
              "appealing to the emotions as well as the eye"
            ]
          }
        },
        "description": "This custom type contains response for definitions endpoint.",
        "example": {
          "word": "lovely",
          "definition": [
            "lovable especially in a childlike or naive way",
            "a very pretty girl who works as a photographer's model",
            "appealing to the emotions as well as the eye"
          ]
        }
      },
      "ExamplesResponse": {
        "title": "ExamplesResponse",
        "type": "object",
        "properties": {
          "word": {
            "type": "string",
            "description": "The word that is searched.",
            "nullable": true,
            "example": "testing"
          },
          "examples": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The usage examples of the searched word.",
            "nullable": true,
            "example": [
              "there are laboratories for commercial testing",
              "it involved testing thousands of children for smallpox",
              "they agreed to end the testing of atomic weapons"
            ]
          }
        },
        "description": "This custom type contains response for examples endpoint.",
        "example": {
          "word": "testing",
          "examples": [
            "there are laboratories for commercial testing",
            "it involved testing thousands of children for smallpox",
            "they agreed to end the testing of atomic weapons"
          ]
        }
      },
      "PronunciationDetails": {
        "title": "PronunciationDetails",
        "type": "object",
        "properties": {
          "all": {
            "type": "string",
            "description": "The pronunciation of the word.",
            "nullable": true,
            "example": "wɪnd"
          },
          "noun": {
            "type": "string",
            "description": "The noun pronunciation of the word.",
            "nullable": true,
            "example": "wɪnd"
          },
          "verb": {
            "type": "string",
            "description": "The verb pronunciation of the word.",
            "nullable": true,
            "example": "waɪnd"
          }
        },
        "description": "This model contains pronunciation details of a specific word.",
        "example": {
          "all": "wɪnd",
          "noun": "wɪnd",
          "verb": "waɪnd"
        }
      },
      "SynonymsResponse": {
        "title": "SynonymsResponse",
        "type": "object",
        "properties": {
          "word": {
            "type": "string",
            "description": "The word that is searched.",
            "nullable": true,
            "example": "lovely"
          },
          "synonyms": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The synonyms of the searched word.",
            "nullable": true,
            "example": [
              "adorable",
              "endearing",
              "cover girl",
              "pin-up"
            ]
          }
        },
        "description": "This custom type contains response for synonyms endpoint.",
        "example": {
          "word": "lovely",
          "synonyms": [
            "adorable",
            "endearing",
            "cover girl",
            "pin-up"
          ]
        }
      },
      "FrequencyResponse": {
        "title": "FrequencyResponse",
        "type": "object",
        "properties": {
          "word": {
            "type": "string",
            "description": "The word that is searched.",
            "nullable": true,
            "example": "testing"
          },
          "frequency": {
            "$ref": "#/components/schemas/FrequencyDetails"
          }
        },
        "description": "This custom type contains response for frequency endpoint.",
        "example": {
          "word": "wind",
          "frequency": {
            "zipf": 4.81,
            "perMillion": 64.22,
            "diversity": 0.2
          }
        }
      },
      "WordDetails": {
        "title": "WordDetails",
        "type": "object",
        "properties": {
          "definition": {
            "type": "string",
            "description": "Explains the definition of the word.",
            "nullable": true,
            "example": "an examination of the characteristics of something."
          },
          "partOfSpeech": {
            "type": "string",
            "description": "Explains what part of speech the word is.",
            "nullable": true,
            "example": "noun"
          },
          "synonyms": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The list of synonyms.",
            "nullable": true,
            "example": [
              "examination"
            ]
          },
          "typeOf": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "List of words that are more general than the searched word.",
            "nullable": true,
            "example": [
              "examination",
              "scrutiny"
            ]
          },
          "hasTypes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "More specific examples of types of searched word.",
            "nullable": true,
            "example": [
              "screening"
            ]
          },
          "derivation": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The derivation if any.",
            "nullable": true,
            "example": [
              "test"
            ]
          },
          "examples": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The usage examples of word if any.",
            "nullable": true,
            "example": [
              "there are laboratories for commercial testing",
              "it involved testing thousands of children for smallpox"
            ]
          },
          "antonyms": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "List of antonyms for the searched word.",
            "nullable": true,
            "example": [
              "unwind"
            ]
          },
          "verbGroup": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The verb group of the searched word.",
            "nullable": true,
            "example": [
              "wander"
            ]
          },
          "hasParts": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Words that are parts of the searched word.",
            "nullable": true,
            "example": [
              "mouthpiece",
              "bell",
              "embouchure"
            ]
          },
          "hasSubstances": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Words that are substances of the searched word.",
            "nullable": true,
            "example": [
              "air"
            ]
          },
          "entails": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Words that are implied by the searched word. Usually used for verbs.",
            "nullable": true,
            "example": [
              "turn"
            ]
          }
        },
        "description": "This custom type stores word information.",
        "example": {
          "definition": "coil the spring of (some mechanical device) by turning a stem",
          "partOfSpeech": "verb",
          "synonyms": [
            "wind up"
          ],
          "entails": [
            "turn"
          ],
          "typeOf": [
            "fasten",
            "tighten"
          ],
          "hasTypes": [
            "rewind"
          ],
          "derivation": [
            "winder"
          ],
          "examples": [
            "wind your watch"
          ]
        }
      },
      "WordResponse": {
        "title": "WordResponse",
        "type": "object",
        "properties": {
          "word": {
            "type": "string",
            "description": "The word that is searched.",
            "nullable": true,
            "example": "testing"
          },
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/WordDetails"
            },
            "description": "This field contains detailed information of the word.",
            "nullable": true,
            "example": [
              {
                "definition": "the act of giving students or candidates a test (as by questions) to determine what they know or have learned",
                "partOfSpeech": "noun",
                "synonyms": [
                  "examination"
                ],
                "typeOf": [
                  "investigating",
                  "investigation"
                ],
                "hasTypes": [
                  "11-plus",
                  "eleven-plus"
                ],
                "derivation": [
                  "test"
                ]
              },
              {
                "definition": "an examination of the characteristics of something",
                "partOfSpeech": "noun",
                "typeOf": [
                  "examination",
                  "scrutiny"
                ],
                "hasTypes": [
                  "screening"
                ],
                "derivation": [
                  "test"
                ],
                "examples": [
                  "there are laboratories for commercial testing",
                  "it involved testing thousands of children for smallpox"
                ]
              },
              {
                "definition": "the act of subjecting to experimental test in order to determine how well something works",
                "partOfSpeech": "noun",
                "typeOf": [
                  "experimentation",
                  "experiment"
                ],
                "derivation": [
                  "test"
                ],
                "examples": [
                  "they agreed to end the testing of atomic weapons"
                ]
              }
            ]
          },
          "pronunciation": {
            "type": "object",
            "description": "This model contains pronunciation details of a specific word.",
            "nullable": true,
            "example": {
              "all": "wɪnd",
              "noun": "wɪnd",
              "verb": "waɪnd"
            }
          },
          "frequency": {
            "type": "number",
            "description": "The frequency of the word usage.",
            "nullable": true,
            "example": 4.14
          },
          "syllables": {
            "$ref": "#/components/schemas/syllableDetails"
          }
        },
        "description": "This custom type contains the response for word API.",
        "example": {
          "word": "wind",
          "results": [
            {
              "definition": "raise or haul up with or as if with mechanical help",
              "partOfSpeech": "verb",
              "synonyms": [
                "hoist",
                "lift"
              ],
              "typeOf": [
                "raise",
                "lift",
                "get up",
                "elevate",
                "bring up"
              ],
              "hasTypes": [
                "trice up",
                "trice"
              ]
            },
            {
              "definition": "catch the scent of; get wind of",
              "partOfSpeech": "verb",
              "synonyms": [
                "nose",
                "scent"
              ],
              "typeOf": [
                "smell"
              ]
            },
            {
              "definition": "a reflex that expels intestinal gas through the anus",
              "partOfSpeech": "noun",
              "synonyms": [
                "breaking wind",
                "fart",
                "farting",
                "flatus"
              ],
              "typeOf": [
                "reflex",
                "instinctive reflex",
                "innate reflex",
                "reflex action",
                "physiological reaction",
                "unconditioned reflex",
                "inborn reflex",
                "reflex response"
              ]
            },
            {
              "definition": "form into a wreath",
              "partOfSpeech": "verb",
              "synonyms": [
                "wreathe"
              ],
              "typeOf": [
                "twine",
                "intertwine",
                "lace",
                "entwine",
                "enlace",
                "interlace"
              ]
            },
            {
              "definition": "empty rhetoric or insincere or exaggerated talk",
              "partOfSpeech": "noun",
              "synonyms": [
                "idle words",
                "jazz",
                "malarkey",
                "malarky",
                "nothingness"
              ],
              "typeOf": [
                "talking",
                "talk"
              ],
              "derivation": [
                "windy"
              ],
              "examples": [
                "that's a lot of wind"
              ]
            },
            {
              "definition": "arrange or or coil around",
              "partOfSpeech": "verb",
              "synonyms": [
                "roll",
                "twine",
                "wrap"
              ],
              "typeOf": [
                "displace",
                "move"
              ],
              "hasTypes": [
                "loop",
                "ball",
                "spool",
                "clew",
                "clue",
                "coil",
                "curl",
                "reel"
              ],
              "antonyms": [
                "unwind"
              ],
              "derivation": [
                "winder"
              ]
            },
            {
              "definition": "to move or cause to move in a sinuous, spiral, or circular course",
              "partOfSpeech": "verb",
              "synonyms": [
                "meander",
                "thread",
                "wander",
                "weave"
              ],
              "typeOf": [
                "go",
                "locomote",
                "move",
                "travel"
              ],
              "hasTypes": [
                "snake"
              ],
              "verbGroup": [
                "wander"
              ],
              "examples": [
                "the river winds through the hills"
              ]
            },
            {
              "definition": "extend in curves and turns",
              "partOfSpeech": "verb",
              "synonyms": [
                "curve",
                "twist"
              ],
              "typeOf": [
                "be"
              ],
              "hasTypes": [
                "circumvolute",
                "spiral",
                "snake"
              ],
              "examples": [
                "The road winds around the lake"
              ]
            },
            {
              "definition": "the act of winding or twisting",
              "partOfSpeech": "noun",
              "synonyms": [
                "twist",
                "winding"
              ],
              "typeOf": [
                "rotation",
                "rotary motion"
              ],
              "examples": [
                "he put the key in the old clock and gave it a good wind"
              ]
            },
            {
              "definition": "a musical instrument in which the sound is produced by an enclosed column of air that is moved by bellows or the human breath",
              "partOfSpeech": "noun",
              "synonyms": [
                "wind instrument"
              ],
              "typeOf": [
                "instrument",
                "musical instrument"
              ],
              "hasTypes": [
                "organ pipe",
                "whistle",
                "post horn",
                "brass",
                "pipe",
                "sweet potato",
                "pipe organ",
                "kazoo",
                "pipework",
                "free-reed instrument",
                "ocarina",
                "organ",
                "woodwind instrument",
                "brass instrument",
                "woodwind",
                "wood"
              ],
              "hasParts": [
                "mouthpiece",
                "bell",
                "embouchure"
              ]
            },
            {
              "definition": "air moving (sometimes with considerable force) from an area of high pressure to an area of low pressure",
              "partOfSpeech": "noun",
              "synonyms": [
                "air current",
                "current of air"
              ],
              "typeOf": [
                "weather",
                "weather condition",
                "atmospheric condition",
                "conditions"
              ],
              "hasTypes": [
                "blast",
                "blow",
                "boreas",
                "zephyr",
                "breeze",
                "calm",
                "calm air",
                "catabatic wind",
                "chinook",
                "chinook wind",
                "simoon",
                "sou'easter",
                "sou'wester",
                "air",
                "khamsin",
                "languor",
                "monsoon",
                "north wind",
                "norther",
                "northerly",
                "northwest wind",
                "northwester",
                "squall",
                "prevailing wind",
                "southwester",
                "southerly",
                "souther",
                "southeaster",
                "south wind",
                "samiel",
                "santa ana",
                "simoom",
                "snow eater",
                "crosswind",
                "doldrums",
                "draft",
                "draught",
                "east wind",
                "easter",
                "easterly",
                "airstream",
                "wester",
                "west wind",
                "foehn",
                "fohn",
                "gale",
                "gentle wind",
                "gust",
                "harmattan",
                "headwind",
                "high wind",
                "thermal",
                "tailwind",
                "katabatic wind"
              ],
              "hasSubstances": [
                "air"
              ],
              "derivation": [
                "windy"
              ],
              "examples": [
                "trees bent under the fierce winds",
                "when there is no wind, row"
              ]
            },
            {
              "definition": "coil the spring of (some mechanical device) by turning a stem",
              "partOfSpeech": "verb",
              "synonyms": [
                "wind up"
              ],
              "entails": [
                "turn"
              ],
              "typeOf": [
                "fasten",
                "tighten"
              ],
              "hasTypes": [
                "rewind"
              ],
              "derivation": [
                "winder"
              ],
              "examples": [
                "wind your watch"
              ]
            },
            {
              "definition": "an indication of potential opportunity",
              "partOfSpeech": "noun",
              "synonyms": [
                "confidential information",
                "hint",
                "lead",
                "steer",
                "tip"
              ],
              "typeOf": [
                "direction",
                "counsel",
                "counseling",
                "guidance",
                "counselling"
              ]
            },
            {
              "definition": "a tendency or force that influences events",
              "partOfSpeech": "noun",
              "typeOf": [
                "influence"
              ],
              "examples": [
                "the winds of change"
              ]
            },
            {
              "definition": "breath",
              "partOfSpeech": "noun",
              "typeOf": [
                "expiration",
                "breathing out",
                "exhalation"
              ],
              "examples": [
                "the collision knocked the wind out of him"
              ]
            }
          ],
          "syllables": {
            "count": 1,
            "list": [
              "wind"
            ]
          },
          "pronunciation": {
            "all": "wɪnd",
            "noun": "wɪnd",
            "verb": "waɪnd"
          },
          "frequency": 4.81
        }
      },
      "PronunciationResponse": {
        "title": "PronunciationResponse",
        "type": "object",
        "properties": {
          "word": {
            "type": "string",
            "description": "The word that is searched.",
            "nullable": true,
            "example": "testing"
          },
          "pronunciation": {
            "$ref": "#/components/schemas/PronunciationDetails"
          }
        },
        "description": "This custom type contains response for pronunciation endpoint.",
        "example": {
          "word": "wind",
          "pronunciation": {
            "all": "wɪnd",
            "noun": "wɪnd",
            "verb": "waɪnd"
          }
        }
      },
      "FrequencyDetails": {
        "title": "FrequencyDetails",
        "type": "object",
        "properties": {
          "zipf": {
            "type": "number",
            "description": "Explains the zipf score.",
            "nullable": true,
            "example": 4.82
          },
          "perMillion": {
            "type": "number",
            "description": "Explains the perMillion score.",
            "nullable": true,
            "example": 65.76
          },
          "diversity": {
            "type": "number",
            "description": "Explains the diversity score.",
            "nullable": true,
            "example": 0.17
          }
        },
        "description": "This model contains frequency details of a specific word.",
        "example": {
          "zipf": 4.81,
          "perMillion": 64.22,
          "diversity": 0.2
        }
      },
      "syllableDetails": {
        "title": "syllableDetails",
        "type": "object",
        "properties": {
          "count": {
            "type": "integer",
            "description": "The count of syllables.",
            "format": "int32",
            "nullable": true,
            "example": 5
          },
          "list": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "The list of syllables.",
            "nullable": true,
            "example": [
              "wind"
            ]
          }
        },
        "description": "This custom type contains the syllable details for word API.",
        "example": {
          "count": 1,
          "list": [
            "wind"
          ]
        }
      }
    },
    "securitySchemes": {
      "RapidAPI-Key": {
        "type": "apiKey",
        "description": "This is an API key from RapidAPI.",
        "name": "X-RapidAPI-Key",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "RapidAPI-Key": []
    }
  ],
  "tags": [
    {
      "name": "APIs",
      "description": ""
    }
  ]
}
